version: '3.8'

services:
  db:
    image: postgres:15-bookworm
    container_name: supabase-db
    environment:
      POSTGRES_PASSWORD: buyticle
    volumes:
      - supabase_db_new:/var/lib/postgresql/data
    networks:
      - supabase-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rest:
    # L'image Bitnami est beaucoup plus tolérante sur les IDs utilisateurs
    image: bitnami/postgrest:12
    container_name: supabase-rest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:3000"
    environment:
      # Attention, les noms de variables changent légèrement chez Bitnami
      POSTGREST_DB_URI: postgres://postgres:buyticle@db:5432/postgres
      POSTGREST_DB_SCHEMAS: public
      POSTGREST_JWT_SECRET: jksdfhksdfldjflhslfhljskhflsjhgsdjfhgskjg
      POSTGREST_DB_ANON_ROLE: postgres
    networks:
      - supabase-network
  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    depends_on:
      - rest
    ports:
      - "3001:3000"
    environment:
      SUPABASE_URL: http://rest:3000
      STUDIO_DEFAULT_ORGANIZATION: "Buyticle"
      STUDIO_DEFAULT_PROJECT: "Inventaire"
      # On ajoute ces deux là pour que Studio sache où est l'API
      SUPABASE_REST_URL: http://rest:3000/rest/v1/
    networks:
      - supabase-network

networks:
  supabase-network:
    driver: bridge

volumes:
  supabase_db_new: