version: '3.8'
services:
  supabase:
    # Cette image est plus légère et plus stable pour les petits VPS
    image: supabase/postgres:14.1.0
    container_name: supabase-standalone
    environment:
      POSTGRES_PASSWORD: buyticle
      JWT_SECRET: jksdfhksdfldjflhslfhljskhflsjhgsdjfhgskjg
    ports:
      - "5432:5432"
      - "3000:3000"
      - "8000:8000"
    volumes:
      - supabase_data:/var/lib/postgresql/data
    restart: always

volumes:
  supabase_data: