server {
    listen 80;
    location /storage/v1/ {
        proxy_pass http://storage:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location / {
        proxy_pass http://storage:5000;
        proxy_set_header Host $host;
    }
}