server {
    listen 5001;
    location /storage/v1/ {
        proxy_pass http://localhost:5000/;
        proxy_set_header Host $host;
    }
    location / {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
    }
}
